##### Input Paths #####
input_path: test_input

##### Output Paths ######
output_path: test_output

##### Other Parameters #####
threads: 1
batch_name: test_batch
primer_bed: resources/primers/nCoV-2019-NimaGen-V3.bed
PE_primer_bed: resources/primers/nCoV-2019-NimaGen-PE-V3.bed

##### Resources #####
ref_genome: resources/ref/MN908947.3.fa
