##### Input Paths #####
#Sample sheet would normally be found inside the run directory, e.g runDir/SampleSheet.csv by default
sample_sheet: /path/to/sample/sheet
run_directory: /path/to/run/directory
fastq_directory: /path/to/fastq/directory

##### Output Paths ######
output_path: output
batch_dir: output/batchName
samples_dir: output/batchName/Samples
summary_dir: output/batchName/Summary

##### Other Parameters #####
threads: 7
bcl-convert_threads: 26

##### Resources #####
ref_genome: resources/ref/MN908947.3.fa
primer_bed: resources/primers/primer_V??.bed
PE_primer_bed: resources/primers/primer_PE_V??.bed
ambig_regions: resources/mask/blank_mask

##### Utilities
scripts: utilities/scripts
